### ISSUE TITLE
Not downloading every model / Suggestions

### ISSUE THREAD

**Issue by ResleyZ** [Confuzu/CivitAI-Model-grabber#3]
Hello, first of all, I want to say that I absolutely _love_ this, it saves so unbelievable much time.

I've noticed that with some users, it doesn't download all models. 
For example the user [Dolirama126](https://civitai.com/user/dolirama126/models) has a total of 684 models uploaded. However, when I run the program, using my API key, I only get 94 folders, missing quite some models.

This includes LORA's, embeddings, and (from other creators) also checkpoints, and it's seemingly random which models do and don't get downloaded.

I do get the following error when I use the program, which I'm not sure is something that causes the inability to download all models, or is something different;
```
Traceback (most recent call last): 
  File "F:\AI\CivitAI-Model-grabber-main\civitAI_Model_downloader.py", line 299, in <module>
    if metadata['totalPages'] > 1:
       ~~~~~~~~^^^^^^^^^^^^^^ 
KeyError: 'totalPages'
```

Which refers to;
```
# Check for pagination and handle subsequent pages
if metadata['totalPages'] > 1:
    handle_pagination(metadata)
```

----------------------------------------

Furthermore, I have three suggestions that would make downloading and organizing models much easier (for me at least).

Firstly, is it possible to have my API key stored somewhere, instead of entering it every time?

Secondly, would it be possible to "queue" several creators? At the moment I have several xxx_downloaded folders, and if I want to update these, I have to enter the username, and my API key every single time, which turns into a bit of work if you have a lot of folders. If possible, it would be amazing if I could queue several users, or refer to a file with the usernames in it.

And finally, for the creators that make multiple types of models, would it be possible to download these in seperate folders? So the structure would be something like this;

 <tr>
    <td>
      <pre>
        Creator/
        ├─ Lora/
        │  ├─ Lora1/
        │  │  ├─ Lora1.safetensors
        │  │  ├─ Lora1.jpg
        │  │
        │  ├─ Lora2/
        │  │  ├─ Lora2.safetensors
        │  │  ├─ Lora2.jpg
        │  │
        ├─ Embedding/
        │  ├─ Embedding1/
        │  │  ├─ Embedding1.pt
        │  │  ├─ Embedding1.jpg
        │  │
        │  ├─ Embedding2/
        │  │  ├─ Embedding2.pt
        │  │  ├─ Embedding2.jpg
      </pre>
    </td>

I'm sorry if this is a bit much to ask, but as I'm a bit of a data hoarder, this program made my live so much easier, so thank you again!

**Comment by Confuzu** [comment]
idea no. 1 later, because now you  have only cpoy & paste it once because new feature multiple usernames
idea no. 2 the multiple users is included in the update 
idea no. 3 I have to take a closer look at how I might be able to implement this.

**Comment by ElRandom78** [comment]
Hi everyone, 
hope you all having good and quality time with CIVITAI stuffs .  :)
I encountered same problem noticed by ResleyZ :
unfortunatley, the algorythm download only a portion of the whole folder of files of a Username-Creator of CIVITAI.

For some users, also I have encountered the error:

Traceback (most recent call last): 
  File "F:\AI\CivitAI-Model-grabber-main\civitAI_Model_downloader.py", line 299, in <module>
    if metadata['totalPages'] > 1:
       ~~~~~~~~^^^^^^^^^^^^^^ 
KeyError: 'totalPages'

In others cases not, but still, only a portion of files downloaded, not the whole folder.

If this can be of some help, I post here an example of a download that I tried to make with last update of the Grabber :

**Comment by ElRandom78** [comment]
![Try_downloading_SetusArts_files](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/0155b915-7cf4-49d7-962f-87d01205e30b)

**Comment by ElRandom78** [comment]
Hi everyone,
hope you all having good and quality time with CIVITAI stuffs . :)
I encountered same problem noticed by ResleyZ :
unfortunatley, the algorythm download only a portion of the whole folder of files of a Username-Creator of CIVITAI.

For some users, also I have encountered the error:

Traceback (most recent call last):
File "F:\AI\CivitAI-Model-grabber-main\civitAI_Model_downloader.py", line 299, in
if metadata['totalPages'] > 1:
~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'totalPages'

In others cases not, but still, only a portion of files downloaded, not the whole folder.

If this can be of some help, I post here an example of a download that I tried to make with last update of the Grabber :

![Try_downloading_SetusArts_files](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/97c9c537-f55b-44f2-9ea7-32d080324e5a)

The try that I made It's about SetsuArts user.
In his Civitai user page there are a total of 180 files,
Today I tried to download his files, but the Grabber has downloaded only 53/180 files.

t's like the algoryth totalize an incorrect number of files, on first instance.

Another thing is, "the end of pagination",
maybe related with variable next_page (but I'm not sure).

it's just a hypothesis but, maybe the end of pagination reaches an incorrect end because of that parameter ?

I hope this can be of some help for fixing,
and thank you again for this tool. It's fantastic, really.

**Comment by ElRandom78** [comment]
Hi everyone,
hope you all having good and quality time with CIVITAI stuffs . :)
I encountered same problem noticed by ResleyZ :
unfortunatley, the algorythm download only a portion of the whole folder of files of a Username-Creator of CIVITAI.

For some users, also I have encountered the error:

Traceback (most recent call last):
File "F:\AI\CivitAI-Model-grabber-main\civitAI_Model_downloader.py", line 299, in
if metadata['totalPages'] > 1:

KeyError: 'totalPages'

In others cases not, but still, only a portion of files downloaded, not the whole folder.

If this can be of some help, I post here an example of a download that I tried to make with last update of the Grabber :

![Try_downloading_SetusArts_files](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/688b2ac0-f742-4ee2-a942-a9e1709f204b)

The try that I made It's about SetsuArts user.
In his Civitai user page there are a total of 180 files,
Today I tried to download his files, but the Grabber has downloaded only 53/180 files.

t's like the algoryth totalize an incorrect number of files, on first instance.

Another thing is, "the end of pagination",
maybe related with variable next_page (but I'm not sure).

it's just a hypothesis but, maybe the end of pagination reaches an incorrect end because of that parameter ?

I hope this can be of some help for fixing,
and thank you again for this tool. It's fantastic, really.

**Comment by Confuzu** [comment]
the problem was the new NSFW filter of Civit AI 
i  updated the Code

**Comment by ElRandom78** [comment]
Thank you , from the bottom of my heart, for this fast update, SIr! 
I've already made several tries yesterday, with users like : **Setsuarts**, **flyx3**, **eft**, **narugo1992**, ecc... 
the code worked perfectly, because has downloaded the entirety of all their files posted .

To sum up, I tested the Grabber with creators who have a total of :  180 - 110 - 715 - 1103  files in their CIVITAI pages.
So yeah, I made several tests with different amounts, and all in this cases all went smoothly fine.

For now, 
I've encountered error only with user : **nochekaiser881**, that has more than 3000 files in his CIVITAI page.

I post below here the CMD error :

![error_during_download_user_nochekaiser881](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/dc20dd8c-26e4-4809-aed0-ea9371b2633b)

The code has downloaded only a bit more of 300 files / 3280.

Can you please check and try with this user aslo by your side?

And thanks again for this update.

**Comment by Confuzu** [comment]
The api could not deliver and the script could not handle it and crashed with that error. i try to improve the error handling so that this does not happen again.

**Comment by sergiosaurio** [comment]
I'm trying to download models from the same user (nochekaiser881)
But I got this ouput:

![スクリーンショット 2024-04-10 153400](https://github.com/Confuzu/CivitAI-Model-grabber/assets/6759470/71102a55-b888-4d10-90c9-07bfee08ba03)


I noticed that some of his models are stills in early access
May that be a problem?
![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/6759470/0f614be3-da78-43d9-b233-29884213acdf)

**Comment by Confuzu** [comment]
Yes, that could be the problem, if you don't have access to the early access stuff, then the API can't deliver either.

**Comment by Confuzu** [comment]
i  will  close this one every new bug please open a new Issues

**Comment by ElRandom78** [comment]
Hi. 
Sorry to say, but it seems that the bug persist.
I have tried again several times with same user,

bu It has downloaded only 99 files / 3314.

I post below the result:


```
Microsoft Windows [Versione 10.0.19045.4291]
(c) Microsoft Corporation. Tutti i diritti sono riservati.

H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber>python civitAI_Model_downloader.py nochekaiser881
Please enter your Civitai API token: 775d795c5e309fe91bc036e49d601156
Traceback (most recent call last):
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\civitAI_Model_downloader.py", line 293, in <module>
    process_username(username)
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\civitAI_Model_downloader.py", line 271, in process_username
    result = future.result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\civitAI_Model_downloader.py", line 136, in download_model_files
    os.makedirs(item_dir, exist_ok=True)
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'model_downloads\\nochekaiser881\\C.C. "C2, Immortal Witch, Pizza Girl, Zero\'s Mistress, Grey Witch" - Code Geass: Lelouch of the Rebellion (Code Geass: Hangyaku no Lelouch) (コードギアス 反逆のルルーシュ)'

H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber>

```

![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/5a0167fc-0ba1-4f20-9929-7d0e2f70ec35)

**Comment by ElRandom78** [comment]
I have a question : OSError: [WinError 123] is an error that breaks everything and kill the iteration?

Or what break the download iteration is related with something else?
